Repository wbhoomika/python4beginners-Hacktoberfest22, pull requests merged in 2022-10, with the labels that each got.

#11 Create quick_sort.py
  Python Projects/quick_sort.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#12 Create Pyramid.py
  Python Projects/Pyramid.py
Labels: hacktoberfest-accepted, hacktoberfest, help wanted, good first issue

#13 Added helmet.py
  Python Projects/helmet.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#16 Add script to categorize a folder
  Python Projects/file_organizer.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#14 Hacktoberfest22
  CONTRIBUTING.md
  Python Projects/Vaccine Availability Checker.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#17 Add BalloonShooter.py
  Python Projects/BalloonShooter.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#19 Create Count_game.py
  Python Projects/snake-game.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#20 Create Get_OTP.PY
  Python Projects/Get_OTP.PY
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#21 Create Random_number.py
  Random_number.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#23 Create Different_Set_Operations.py
  Different_Set_Operations.py
Labels: hacktoberfest-accepted, hacktoberfest

#24 Create String_Palindrome or Not.py
  Python Projects/String_Palindrome or Not.py
Labels: hacktoberfest-accepted, hacktoberfest

#26 Create cscan.py
  Python Projects/cscan.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#30 Created A Picture JPEG convertor.
  Python Projects/Image_JPEG_Convertor.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#31 Create Count_Number.py
  Python Projects/Count_Number.py
Labels: hacktoberfest-accepted, hacktoberfest

#32 Armstrong
  CONTRIBUTING.md
  Python Projects/char-ctr.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#36 Added AI gesture volume controller
  Python Projects/AI-Hand-Volume-Controler/README.md
  Python Projects/AI-Hand-Volume-Controler/main.py
  Python Projects/AI-Hand-Volume-Controler/volumecontrol.py
  Python Projects/snakegame.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#33 Beginner program to find max number in a list
  CONTRIBUTING.md
  Python Projects/max_in_list.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#38 Added a rock paper scissors game :)
  CONTRIBUTING.md
  Python Projects/rock_paper_scissors.py
Labels: hacktoberfest-accepted, hacktoberfest, help wanted

#39 Weather application added
  Python Projects/WeatherApp/weather.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#40 Create PasswordStrengthChecker.py
  Python Projects/PasswordStrengthChecker.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#41 Pyramid using python
  Python Projects/Pyramid_in_python.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#42 Added a magic number program using python
  Python Projects/Magic_number.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#43 sorting visualizer
  Python Projects/Sorting visualizer.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#45 Add files via upload
  Python Projects/turtle.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#46 added Python file
  CONTRIBUTING.md
  Python Projects/calculator_dh.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#47 Create Hello world.py
  Python Projects/Hello world.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#48 Simple Figlet Python Program
  CONTRIBUTING.md
  Python Projects/figlet.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#50 Create hangman.py
  Python Projects/hangman.py
  Python Projects/morsecode.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#53 Create bubbleSort.c
  Python Projects/bubbleSort.c
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#55 Added Binary traversal
  Python Projects/binary_tree_traversals.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#56 I have added a new project of standard calculator and .md file is updated.
  CONTRIBUTING.md
  Python Projects/calculator.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#57 Added Hacktoberfest pattern using turtle.
  CONTRIBUTING.md
  Python Projects/hacktober_pattern.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#58 Check for armstrong
  CONTRIBUTING.md
  CheckArmstrongNumber.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#61 Creating TowerofHanoi.py file and adding name to Contributing.md file
  CONTRIBUTING.md
  Python Projects/TowerofHanoi.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#65 Create quadraticSolver.py
  Python Projects/quadraticSolver.py
Labels: hacktoberfest-accepted, hacktoberfest

#70 Add second_largest_score
  Python Projects/second_largest_score.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#72 ping_pong_game.py
  Python Projects/ping pong game.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#73 Create calculate_triangle_area.py
  Python Projects/calculate_triangle_area.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#74 AddedInfoAndProgram
  CONTRIBUTING.md
  Python Projects/HashSet.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#75 Create Pattern.py
  Python Projects/Pattern.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#76 Text Editor Project added
  Python Projects/Text Editor/Text_Editor.py
  Python Projects/Text Editor/icons2/align_center.png
  Python Projects/Text Editor/icons2/align_left.png
  Python Projects/Text Editor/icons2/align_right.png
  Python Projects/Text Editor/icons2/bold.png
  Python Projects/Text Editor/icons2/clear_all.png
  Python Projects/Text Editor/icons2/copy.png
  Python Projects/Text Editor/icons2/cut.png
  Python Projects/Text Editor/icons2/dark.png
  Python Projects/Text Editor/icons2/exit.png
  Python Projects/Text Editor/icons2/find.png
  Python Projects/Text Editor/icons2/font_color.png
  Python Projects/Text Editor/icons2/italic.png
  Python Projects/Text Editor/icons2/light_default.png
  Python Projects/Text Editor/icons2/light_plus.png
  Python Projects/Text Editor/icons2/monokai.png
  Python Projects/Text Editor/icons2/new.png
  Python Projects/Text Editor/icons2/night_blue.png
  Python Projects/Text Editor/icons2/open.png
  Python Projects/Text Editor/icons2/paste.png
  Python Projects/Text Editor/icons2/red.png
  Python Projects/Text Editor/icons2/save.png
  Python Projects/Text Editor/icons2/save_as.png
  Python Projects/Text Editor/icons2/status_bar.png
  Python Projects/Text Editor/icons2/tool_bar.png
  Python Projects/Text Editor/icons2/underline.png
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#79 Adding Subreddit Titles Scraper using python
  CONTRIBUTING.md
  Python Projects/Subreddit Titles Scraper v1.0.py
Labels: hacktoberfest-accepted, hacktoberfest, good first issue

#89 Create c calculator.cpp
  c calculator.cpp
Labels: hacktoberfest-accepted, hacktoberfest, good first issue
